### ISSUE TITLE
Could u help me run this on replit(seriously help) 

### ISSUE THREAD

**Issue by vackyton** [BinBashBanana/gfiles#3]
Could u help me idk which language i choose and what is the start command is it javascript?

**Comment by BinBashBanana** [comment]
choose HTML or Static or something like that

please close this issue if it works

**Comment by BinBashBanana** [comment]
you're going to want to choose the html/css/js one

**Comment by vackyton** [comment]
ok thanks

**Comment by vackyton** [comment]
it works thank you so much <3

**Comment by vackyton** [comment]
also binbash is it ok if i run some of your  things like node unblocker?
Right now i am only using it personally not for others

**Comment by vackyton** [comment]
host this to see ff it is okay i said it is made by u
https://replit.com/@vackyton/gfiles-1#index.html

**Comment by BinBashBanana** [comment]
Yes, go ahead and host what you like (you will need python for pydodge, node.js for node unblocker, etc.) But I would suggest moving the "Made by BinBashBanana, hosted by vackyton" to the top of the page, so that it is not actually in the games list. I don't want people thinking that I actually made the games listed.

**Comment by vackyton** [comment]
ok thanks for letting me use it
